site_name: LoRaWan Gateway - Makerspace Repair-Café Hilpoltstein
site_url: https://github.com/makes-hacks-hip/LoRaWanGateway
nav:
    - Repair-Café: https://www.repaircafe-hilpoltstein.de
    - Makerspace: https://makes-hacks-hip.de
    - Makerspace@Github: https://makes-hacks-hip.github.io
    - Informationssammlung: infos.md
theme: readthedocs
repo_url: https://github.com/makes-hacks-hip/LoRaWanGateway/
edit_uri: edit/main/docs/
